/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Venta;
import dao.VentaDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;
       
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private int idSeleccionado = -1;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        tblVentas.setRowHeight(25);
        tblVentas.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tblVentas.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

        cargarTabla();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tblVentas.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblVentas.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tblVentas.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        
        getContentPane().setBackground(new java.awt.Color(245, 245, 245));
        btnRegistrar.setBackground(new java.awt.Color(33, 150, 243));
        btnRegistrar.setForeground(java.awt.Color.WHITE);
        
        ((javax.swing.JComponent) getContentPane()).setBorder(
        javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
        );

    }
    
    private void limpiarCampos() {
    txtPrecio.setText("");
    txtCosto.setText("");
    txtCantidad.setText("");
    txtPrecio.requestFocus();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnTotalVentas = new javax.swing.JButton();
        btnTotalGanancias = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnHistorial = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        javax.swing.JButton btnEliminarTodas = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Precio");

        jLabel2.setText("Costo");

        jLabel3.setText("Cantidad");

        lblResultado.setText("Resultado");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        txtCantidad.setText("jTextField1");
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar Venta");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnTotalVentas.setText("Mostrar Total Ventas");
        btnTotalVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalVentasActionPerformed(evt);
            }
        });

        btnTotalGanancias.setText("Mostrar Total Ganancias");
        btnTotalGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalGananciasActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Precio", "Cantidad", "Total", "Ganancia"
            }
        ));
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVentas);

        btnHistorial.setText("Mostrar Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar Venta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEliminarTodas.setText("Eliminar Todas ");
        btnEliminarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodasActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.setToolTipText("");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCosto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnRegistrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminarTodas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTotalGanancias))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHistorial))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnActualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarTodas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnTotalVentas)
                    .addComponent(btnTotalGanancias))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarTabla() {

    VentaDAO ventaDAO = new VentaDAO();
    List<Object[]> lista = ventaDAO.obtenerVentas();

    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("ID");
    modelo.addColumn("Fecha");
    modelo.addColumn("Precio");
    modelo.addColumn("Costo");
    modelo.addColumn("Cantidad");
    modelo.addColumn("Total");
    modelo.addColumn("Ganancia");

    tblVentas.setModel(modelo);

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    for (Object[] fila : lista) {

        Object fechaObj = fila[1]; // La fecha está en la columna 1 (después del ID)

        String fechaFormateada = "";

        if (fechaObj instanceof LocalDate) {
            fechaFormateada = ((LocalDate) fechaObj).format(formatter);
        } else if (fechaObj instanceof java.sql.Date) {
            fechaFormateada = ((java.sql.Date) fechaObj).toLocalDate().format(formatter);
        }

        modelo.addRow(new Object[]{
            fila[0],                 // ID
            fechaFormateada,         // Fecha formateada
            fila[2],                 // Precio
            fila[3],                 // Costo
            fila[4],                 // Cantidad
            fila[5],                 // Total
            fila[6]                  // Ganancia
        });
    }
   }
    
    private Venta obtenerVentaDesdeCampos(boolean incluirId) {

    if (txtPrecio.getText().trim().isEmpty() ||
        txtCosto.getText().trim().isEmpty() ||
        txtCantidad.getText().trim().isEmpty()) {

        lblResultado.setText("Todos los campos son obligatorios.");
        return null;
    }

    double precio;
    double costo;
    int cantidad;

    try {
        precio = Double.parseDouble(txtPrecio.getText());
        costo = Double.parseDouble(txtCosto.getText());
        cantidad = Integer.parseInt(txtCantidad.getText());
    } catch (NumberFormatException e) {
        lblResultado.setText("Ingrese valores numéricos válidos.");
        return null;
    }

    if (precio <= 0 || costo <= 0 || cantidad <= 0) {
        lblResultado.setText("Los valores deben ser mayores a cero.");
        return null;
    }
    LocalDate fecha = LocalDate.now();
    if (incluirId) {
        return new Venta(idSeleccionado, precio, costo, cantidad, fecha);
    } else {
        return new Venta(precio, costo, cantidad, fecha);
    }
}
    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        Venta venta = obtenerVentaDesdeCampos(false);

        if (venta == null) {
            return;
        }

        VentaDAO ventaDAO = new VentaDAO();
        boolean guardado = ventaDAO.guardarVenta(venta);

        if (guardado) {
        lblResultado.setText("Venta registrada correctamente.");
        cargarTabla();
        limpiarCampos();
        tblVentas.clearSelection();
        } else {
            lblResultado.setText("Error al registrar la venta.");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnTotalVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalVentasActionPerformed
        VentaDAO ventaDAO = new VentaDAO();
        double total = ventaDAO.obtenerTotalVentas();

        lblResultado.setText("Total acumulado de ventas: $" + total);

    }//GEN-LAST:event_btnTotalVentasActionPerformed

    private void btnTotalGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalGananciasActionPerformed
        VentaDAO ventaDAO = new VentaDAO();
        double totalGanancia = ventaDAO.obtenerTotalGanancias();

        lblResultado.setText("Total de ganancias: $" + totalGanancia);

    }//GEN-LAST:event_btnTotalGananciasActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int filaSeleccionada = tblVentas.getSelectedRow();

    if (filaSeleccionada == -1) {
        lblResultado.setText("Seleccione una venta para eliminar.");
        return;
    }

    int id = (int) tblVentas.getValueAt(filaSeleccionada, 0);

    VentaDAO ventaDAO = new VentaDAO();
    boolean eliminado = ventaDAO.eliminarVenta(id);

    if (eliminado) {
        lblResultado.setText("Venta eliminada correctamente.");
        cargarTabla();
    } else {
    lblResultado.setText("Error al eliminar la venta.");
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEliminarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodasActionPerformed
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de eliminar TODAS las ventas?",
        "Confirmar",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {

        VentaDAO ventaDAO = new VentaDAO();
        boolean eliminado = ventaDAO.eliminarTodas();

        if (eliminado) {
            lblResultado.setText("Todas las ventas fueron eliminadas.");
            cargarTabla();
        } else {
            lblResultado.setText("Error al eliminar las ventas.");
        }
    }

    }//GEN-LAST:event_btnEliminarTodasActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMouseClicked
        int fila = tblVentas.getSelectedRow();

    if (fila == -1) {
        return;
    }

    idSeleccionado = (int) tblVentas.getValueAt(fila, 0);

    txtPrecio.setText(tblVentas.getValueAt(fila, 1).toString());
    txtCosto.setText(tblVentas.getValueAt(fila, 2).toString());
    txtCantidad.setText(tblVentas.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tblVentasMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (idSeleccionado == -1) {
            lblResultado.setText("Seleccione una venta para actualizar.");
             return;
        }

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Desea actualizar esta venta?",
            "Confirmar actualización",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        Venta venta = obtenerVentaDesdeCampos(true);

        if (venta == null) {
        return;
        }

        VentaDAO ventaDAO = new VentaDAO();
        boolean actualizado = ventaDAO.actualizarVenta(venta);

        if (actualizado) {
            lblResultado.setText("Venta actualizada correctamente.");
            cargarTabla();
            limpiarCampos();
            tblVentas.clearSelection();
            idSeleccionado = -1;
        } else {
            lblResultado.setText("Error al actualizar la venta.");
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnTotalGanancias;
    private javax.swing.JButton btnTotalVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
